<?php
/**
 * Alternative to the Debug Test
 */


/**
 * Implements hook_page_alter().
 */

function debug_mangler_page_alter(&$page) {
  // Add help text to the user login block.
  /*
   *$page['sidebar_first']['user_login']['help'] = array(
   *  '#weight' => -10,
   *  '#markup' => t('To post comments or add new content, you first have to log in.'),
   *);
   */
  if (arg(0) == 'debug') {
    dsm($page);
    $page['content']['system_main']['renderable_element']['#type'] = 'ol';
  }

}
